# Generated by Django 5.2.6 on 2025-09-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_remove_budgetalert_category_and_more'),
        ('invoices', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='category',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoices_categor_dea933_idx',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
