# Generated by Django 5.2.6 on 2025-09-28 07:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('monthly_limit', 'Monthly Spending Limit'), ('category_limit', 'Category Spending Limit'), ('vendor_limit', 'Vendor Spending Limit'), ('unusual_expense', 'Unusual Expense Pattern')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('triggered', 'Triggered'), ('dismissed', 'Dismissed'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('threshold_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('message', models.TextField(blank=True)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget Alert',
                'verbose_name_plural': 'Budget Alerts',
                'db_table': 'budget_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('week', models.PositiveIntegerField(blank=True, null=True)),
                ('day', models.PositiveIntegerField(blank=True, null=True)),
                ('quarter', models.PositiveIntegerField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_invoices', models.PositiveIntegerField(default=0)),
                ('avg_invoice_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('category_breakdown', models.JSONField(default=dict)),
                ('vendor_breakdown', models.JSONField(default=dict)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Expense Summary',
                'verbose_name_plural': 'Expense Summaries',
                'db_table': 'expense_summaries',
            },
        ),
        migrations.CreateModel(
            name='SpendingTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('total_spent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('previous_month_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('percentage_change', models.FloatField(default=0.0)),
                ('top_category_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('top_vendor_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('insights', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spending Trend',
                'verbose_name_plural': 'Spending Trends',
                'db_table': 'spending_trends',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='UserDashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_month_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('current_month_invoices', models.PositiveIntegerField(default=0)),
                ('current_month_pending', models.PositiveIntegerField(default=0)),
                ('ytd_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('ytd_invoices', models.PositiveIntegerField(default=0)),
                ('total_lifetime_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_lifetime_invoices', models.PositiveIntegerField(default=0)),
                ('ai_processed_count', models.PositiveIntegerField(default=0)),
                ('ai_processing_accuracy', models.FloatField(default=0.0)),
                ('avg_monthly_spending', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Dashboard Metrics',
                'verbose_name_plural': 'User Dashboard Metrics',
                'db_table': 'user_dashboard_metrics',
            },
        ),
    ]
