# Generated by Django 5.2.6 on 2025-09-28 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetalert',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.vendor'),
        ),
        migrations.AddField(
            model_name='expensesummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spendingtrend',
            name='top_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.category'),
        ),
        migrations.AddField(
            model_name='spendingtrend',
            name='top_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.vendor'),
        ),
        migrations.AddField(
            model_name='spendingtrend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_trends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdashboardmetrics',
            name='favorite_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.category'),
        ),
        migrations.AddField(
            model_name='userdashboardmetrics',
            name='favorite_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.vendor'),
        ),
        migrations.AddField(
            model_name='userdashboardmetrics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='expensesummary',
            index=models.Index(fields=['user', 'period_type', 'year'], name='expense_sum_user_id_9b31e3_idx'),
        ),
        migrations.AddIndex(
            model_name='expensesummary',
            index=models.Index(fields=['user', 'year', 'month'], name='expense_sum_user_id_132136_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expensesummary',
            unique_together={('user', 'period_type', 'year', 'month', 'week', 'day', 'quarter')},
        ),
        migrations.AlterUniqueTogether(
            name='spendingtrend',
            unique_together={('user', 'year', 'month')},
        ),
    ]
