# Generated by Django 5.2.6 on 2025-09-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetalert',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expensesummary',
            name='category_breakdown',
        ),
        migrations.RemoveField(
            model_name='spendingtrend',
            name='top_category',
        ),
        migrations.RemoveField(
            model_name='spendingtrend',
            name='top_category_amount',
        ),
        migrations.RemoveField(
            model_name='userdashboardmetrics',
            name='favorite_category',
        ),
        migrations.AlterField(
            model_name='budgetalert',
            name='alert_type',
            field=models.CharField(choices=[('monthly_limit', 'Monthly Spending Limit'), ('vendor_limit', 'Vendor Spending Limit'), ('unusual_expense', 'Unusual Expense Pattern')], max_length=20),
        ),
    ]
