# Generated by Django 5.2.6 on 2025-09-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProcessingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('data_extraction', 'Data Extraction'), ('categorization', 'Invoice Categorization'), ('duplicate_detection', 'Duplicate Detection'), ('summary_generation', 'Summary Generation'), ('vendor_extraction', 'Vendor Information Extraction')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ai_model_version', models.CharField(blank=True, max_length=50)),
                ('processing_node', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Processing Task',
                'verbose_name_plural': 'AI Processing Tasks',
                'db_table': 'ai_processing_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
