# Generated by Django 5.2.6 on 2025-09-28 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_processing', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprocessingtask',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tasks', to='invoices.invoice'),
        ),
        migrations.AddIndex(
            model_name='aiprocessingtask',
            index=models.Index(fields=['invoice', 'task_type'], name='ai_processi_invoice_cc9d72_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprocessingtask',
            index=models.Index(fields=['status', 'created_at'], name='ai_processi_status_ea756e_idx'),
        ),
    ]
